name: C++ CI

on:
  push:
    branches:
      - main
      - feature/parallel
  pull_request:
    branches:
      - main
      - feature/parallel

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Create images folder and dummy input
      run: |
        mkdir -p images
        dd if=/dev/zero bs=1 count=54 of=images/input_image.bmp

    - name: Build the project
      run: |
        make

    - name: Run the program
      run: |
        ./lab

    - name: Clean build artifacts
      run: |
        make clean